package com.ecommerceOn.ecommerceOn.enums;

public enum StatusOrder {

	ADDED_SUCCESSFULY,
	UPDATED_SUCCESSFULY,
	CREATED_SUCCESSFULY,
	QTY_NOT_AVAILABLE,
	DELETE_SUCCESFULY,
	DELETE_UNSUCCESFULY,
	
}
